name: Docker Image CI

on:
  push:
    tags: [ '*' ]
    branches: [ master ]
    paths: [ 'Dockerfile' ]
  pull_request:
    branches: [ master ]
    paths: [ 'Dockerfile' ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Build and optionally push docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: labwaller/base
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/master') }}
